ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BLOG_TAXONOMY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BLOG_TAXONOMY_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BLOG_TAXONOMY_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BLOG_TAXONOMY_MERGED';
