export const AUDIT_ACTIONS = [
  "business_service_status_changed",
  "business_service_assigned",
  "business_service_removed",
  "business_status_changed",
  "user_role_changed",
  "admin_login_checked",
  "service_catalog_created",
  "service_catalog_updated",
  "service_catalog_deleted",
  "business_member_added",
  "business_member_removed",
  "business_ownership_transferred",
  "service_plan_created",
  "service_plan_updated",
  "service_plan_archived",
  "subscription_paused",
  "subscription_resumed",
  "subscription_canceled",
  "provisioning_job_retried",
  "user_status_changed",
  "user_sessions_revoked",
  "access_role_created",
  "access_role_updated",
  "user_created",
  "user_profile_updated",
  "subscription_created",
  "subscription_renewed",
  "subscription_plan_changed",
  "order_note_updated",
  "order_canceled",
  "order_expired",
  "business_created",
  "business_profile_updated",
  "business_archived",
  "business_restored",
  "automation_connector_updated",
  "automation_connector_cleared",
  "support_ticket_created",
  "support_ticket_updated",
  "support_ticket_replied",
  "consultation_lead_updated",
  "blog_post_created",
  "blog_post_updated",
  "blog_post_submitted",
  "blog_post_published",
  "blog_post_archived",
  "blog_post_scheduled",
  "blog_post_unpublished",
  "blog_post_revision_restored",
  "blog_post_deleted",
  "site_seo_updated",
  "faq_settings_updated",
  "blog_media_uploaded",
  "blog_media_updated",
  "blog_media_deleted",
  "blog_taxonomy_created",
  "blog_taxonomy_updated",
  "blog_taxonomy_deleted",
  "blog_taxonomy_merged",
  "custom_service_created",
  "custom_service_updated",
  "custom_service_offer_created",
  "custom_service_offer_sent",
  "custom_service_offer_canceled",
  "custom_service_offer_paid",
  "custom_service_offer_updated",
  "custom_service_offer_expired",
  "custom_service_subscription_paused",
  "custom_service_subscription_resumed",
  "custom_service_subscription_ended",
  "custom_service_subscription_extended",
] as const;

export type AuditActionValue = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_LABELS: Record<AuditActionValue, string> = {
  business_service_status_changed: "تغییر وضعیت سرویس کسب‌وکار",
  business_service_assigned: "تخصیص سرویس به کسب‌وکار",
  business_service_removed: "حذف سرویس از کسب‌وکار",
  business_status_changed: "تغییر وضعیت کسب‌وکار",
  user_role_changed: "تغییر نقش کاربر",
  admin_login_checked: "بررسی ورود مدیر",
  service_catalog_created: "ایجاد سرویس در کاتالوگ",
  service_catalog_updated: "ویرایش سرویس کاتالوگ",
  service_catalog_deleted: "حذف سرویس از کاتالوگ",
  business_member_added: "افزودن عضو کسب‌وکار",
  business_member_removed: "حذف عضو کسب‌وکار",
  business_ownership_transferred: "انتقال مالکیت کسب‌وکار",
  service_plan_created: "ایجاد پلن سرویس",
  service_plan_updated: "ویرایش پلن سرویس",
  service_plan_archived: "بایگانی پلن سرویس",
  subscription_paused: "توقف اشتراک",
  subscription_resumed: "ادامه اشتراک",
  subscription_canceled: "لغو اشتراک",
  provisioning_job_retried: "تلاش مجدد راه‌اندازی سرویس",
  user_status_changed: "تغییر وضعیت حساب کاربر",
  user_sessions_revoked: "خروج کاربر از همه دستگاه‌ها",
  access_role_created: "ایجاد نقش دسترسی",
  access_role_updated: "ویرایش نقش دسترسی",
  user_created: "ایجاد حساب کاربر",
  user_profile_updated: "ویرایش اطلاعات کاربر",
  subscription_created: "ایجاد دستی اشتراک",
  subscription_renewed: "تمدید دستی اشتراک",
  subscription_plan_changed: "تغییر پلن اشتراک",
  order_note_updated: "ویرایش یادداشت سفارش",
  order_canceled: "لغو مدیریتی سفارش",
  order_expired: "منقضی‌کردن سفارش",
  business_created: "ایجاد کسب‌وکار",
  business_profile_updated: "ویرایش مشخصات کسب‌وکار",
  business_archived: "آرشیو کسب‌وکار",
  business_restored: "بازیابی کسب‌وکار",
  automation_connector_updated: "ویرایش اتصال اتوماسیون سرویس",
  automation_connector_cleared: "پاک‌کردن اتصال اتوماسیون سرویس",
  support_ticket_created: "ایجاد تیکت پشتیبانی",
  support_ticket_updated: "ویرایش وضعیت تیکت پشتیبانی",
  support_ticket_replied: "پاسخ به تیکت پشتیبانی",
  consultation_lead_updated: "ویرایش وضعیت درخواست مشاوره",
  blog_post_created: "ایجاد مقاله وبلاگ",
  blog_post_updated: "ویرایش مقاله وبلاگ",
  blog_post_submitted: "ارسال مقاله برای بررسی",
  blog_post_published: "انتشار مقاله وبلاگ",
  blog_post_archived: "آرشیو مقاله وبلاگ",
  blog_post_scheduled: "زمان‌بندی انتشار مقاله",
  blog_post_unpublished: "لغو انتشار مقاله",
  blog_post_revision_restored: "بازیابی نسخه قبلی مقاله",
  blog_post_deleted: "حذف مقاله وبلاگ",
  site_seo_updated: "ویرایش تنظیمات SEO سایت",
  faq_settings_updated: "ویرایش تنظیمات FAQ",
  blog_media_uploaded: "آپلود رسانه وبلاگ",
  blog_media_updated: "ویرایش رسانه وبلاگ",
  blog_media_deleted: "حذف رسانه وبلاگ",
  blog_taxonomy_created: "ایجاد دسته یا برچسب وبلاگ",
  blog_taxonomy_updated: "ویرایش دسته یا برچسب وبلاگ",
  blog_taxonomy_deleted: "حذف دسته یا برچسب وبلاگ",
  blog_taxonomy_merged: "ادغام دسته یا برچسب وبلاگ",
  custom_service_created: "ایجاد سرویس اختصاصی",
  custom_service_updated: "ویرایش سرویس اختصاصی",
  custom_service_offer_created: "ایجاد پیشنهاد اختصاصی",
  custom_service_offer_sent: "ارسال پیشنهاد اختصاصی",
  custom_service_offer_canceled: "لغو پیشنهاد اختصاصی",
  custom_service_offer_paid: "پرداخت پیشنهاد اختصاصی",
  custom_service_offer_updated: "ویرایش پیشنهاد اختصاصی",
  custom_service_offer_expired: "انقضای پیشنهاد اختصاصی",
  custom_service_subscription_paused: "توقف اشتراک اختصاصی",
  custom_service_subscription_resumed: "ادامه اشتراک اختصاصی",
  custom_service_subscription_ended: "پایان اشتراک اختصاصی",
  custom_service_subscription_extended: "تمدید اشتراک اختصاصی",
};

export const AUDIT_TARGET_TYPES = [
  "business-service",
  "business",
  "user",
  "system",
  "service-catalog",
  "service-plan",
  "subscription",
  "provisioning-job",
  "access-role",
  "order",
  "automation-connector",
  "support-ticket",
  "consultation-lead",
  "blog-post",
  "blog-media",
  "blog-taxonomy",
  "custom-service",
  "custom-service-offer",
  "custom-service-subscription",
  "seo-page",
  "faq-page",
] as const;

export type AuditTargetType = (typeof AUDIT_TARGET_TYPES)[number];

export const AUDIT_TARGET_LABELS: Record<AuditTargetType, string> = {
  "business-service": "سرویس کسب‌وکار",
  business: "کسب‌وکار",
  user: "کاربر",
  system: "سیستم",
  "service-catalog": "کاتالوگ سرویس",
  "service-plan": "پلن سرویس",
  subscription: "اشتراک",
  "provisioning-job": "کار راه‌اندازی سرویس",
  "access-role": "نقش دسترسی",
  order: "سفارش",
  "automation-connector": "اتصال اتوماسیون",
  "support-ticket": "تیکت پشتیبانی",
  "consultation-lead": "درخواست مشاوره",
  "blog-post": "مقاله وبلاگ",
  "blog-media": "رسانه وبلاگ",
  "blog-taxonomy": "دسته یا برچسب وبلاگ",
  "custom-service": "سرویس اختصاصی",
  "custom-service-offer": "پیشنهاد اختصاصی",
  "custom-service-subscription": "اشتراک اختصاصی",
  "seo-page": "صفحه SEO",
  "faq-page": "صفحه سوالات متداول",
};

export function isAuditAction(value: unknown): value is AuditActionValue {
  return (
    typeof value === "string" &&
    (AUDIT_ACTIONS as readonly string[]).includes(value)
  );
}

export function isAuditTargetType(value: unknown): value is AuditTargetType {
  return (
    typeof value === "string" &&
    (AUDIT_TARGET_TYPES as readonly string[]).includes(value)
  );
}

export function getAuditActionLabel(value: string) {
  return isAuditAction(value) ? AUDIT_ACTION_LABELS[value] : value;
}

export function getAuditTargetLabel(value: string) {
  return isAuditTargetType(value) ? AUDIT_TARGET_LABELS[value] : value;
}
