ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_PROFILE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BUSINESS_RESTORED';
