"use client";

import { type FormEvent, useState } from "react";
import Link from "next/link";
import { CheckCircle2, FileSpreadsheet, Send, ShieldCheck } from "lucide-react";

const inputClass="font-ui h-12 w-full rounded-control border border-marketing-border bg-marketing-background/70 px-3 text-sm text-marketing-text outline-none transition placeholder:text-marketing-text-subtle focus:border-service-accent/50 focus:ring-2 focus:ring-service-accent/10";

export default function ExcelPilotForm(){
  const [submitting,setSubmitting]=useState(false); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const phone=String(data.get("phone")??"").replace(/\s|-/g,"");if(!/^09\d{9}$/.test(phone)){setError("لطفاً شماره موبایل معتبر وارد کنید.");return;}
    const fileSubject=String(data.get("fileSubject")??"");const fileSize=String(data.get("fileSize")??"");const currentMethod=String(data.get("currentMethod")??"");const mainQuestion=String(data.get("mainQuestion")??"");const sensitiveData=String(data.get("sensitiveData")??"");const userNote=String(data.get("note")??"").trim();
    const note=[fileSubject?`موضوع فایل: ${fileSubject}`:"",fileSize?`اندازه تقریبی: ${fileSize}`:"",currentMethod?`روش فعلی تحلیل: ${currentMethod}`:"",mainQuestion?`سؤال اصلی: ${mainQuestion}`:"",sensitiveData?`وجود داده حساس: ${sensitiveData}`:"",userNote?`توضیح تکمیلی: ${userNote}`:""].filter(Boolean).join("\n");
    setSubmitting(true);setError("");try{const response=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),phone,businessName:data.get("businessName"),businessType:fileSubject,need:"درخواست تحلیل آزمایشی اکسل",channel:"اکسل",note,website:data.get("website"),source:"excel-analysis-pilot",consent:data.get("consent")==="on"})});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||"ثبت درخواست انجام نشد.");form.reset();setSubmitted(true);}catch(cause){setError(cause instanceof Error?cause.message:"ثبت درخواست انجام نشد.");}finally{setSubmitting(false);}}
  return <section id="excel-pilot" dir="rtl" className="scroll-mt-24 border-t border-marketing-border bg-[linear-gradient(180deg,#07101D,#050A13)] px-4 py-24 sm:px-6 sm:py-28 lg:px-8"><div className="relative mx-auto grid max-w-[1120px] overflow-hidden rounded-[30px] border border-service-accent/20 bg-marketing-surface/70 shadow-[0_35px_100px_rgba(0,0,0,.32)] lg:grid-cols-[.78fr_1.22fr]">
    <div className="relative overflow-hidden border-b border-marketing-border p-7 sm:p-9 lg:border-b-0 lg:border-l lg:p-10"><div className="pointer-events-none absolute -right-24 -top-24 size-[320px] rounded-full bg-service-accent/[0.1] blur-[90px]"/><div className="relative"><div className="font-ui inline-flex items-center gap-2 rounded-full border border-service-accent/20 bg-service-accent/[0.08] px-3 py-1.5 text-[10.5px] font-semibold text-service-accent"><FileSpreadsheet size={14}/> درخواست تحلیل آزمایشی</div><h2 className="font-display mt-5 text-3xl font-black leading-[1.65] text-marketing-text">ببینیم فایل شما چه سؤال مدیریتی را می‌تواند پاسخ دهد</h2><p className="font-ui mt-4 text-[12.5px] leading-8 text-marketing-text-muted">مشخصات کلی فایل و مسئله‌تان را ثبت کنید؛ در این مرحله نیازی به ارسال خود فایل نیست.</p><ul className="mt-7 space-y-3">{["بررسی تناسب ساختار فایل با تحلیل", "تعیین سؤال و خروجی مورد انتظار", "توضیح محدودیت‌ها و مسیر اجرای آزمایشی"].map(item=><li key={item} className="font-ui flex items-center gap-2 text-[11.5px] text-marketing-text-muted"><CheckCircle2 size={15} className="text-emerald-400"/>{item}</li>)}</ul><div className="font-ui mt-7 flex items-start gap-2 rounded-card border border-marketing-border bg-white/[0.025] p-3 text-[10.5px] leading-6 text-marketing-text-subtle"><ShieldCheck size={15} className="mt-1 shrink-0 text-service-accent"/>این فرم فایل دریافت نمی‌کند. ثبت درخواست نیز به‌معنی خرید یا شروع خودکار پردازش نیست.</div></div></div>
    <div className="p-6 sm:p-8 lg:p-10">{submitted?<div role="status" className="flex min-h-[570px] flex-col items-center justify-center text-center"><div className="flex size-16 items-center justify-center rounded-full border border-emerald-400/20 bg-emerald-400/[0.07] text-emerald-400"><CheckCircle2 size={30}/></div><h3 className="font-display mt-5 text-2xl font-bold text-marketing-text">درخواست شما ثبت شد</h3><p className="font-ui mt-3 max-w-md text-sm leading-7 text-marketing-text-muted">درخواست تحلیل آزمایشی در Binix ذخیره شد و از پنل مدیریت قابل پیگیری است.</p><button type="button" onClick={()=>setSubmitted(false)} className="font-ui mt-6 text-xs font-semibold text-service-accent">ثبت درخواست دیگر</button></div>:<form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
      <Field label="نام و نام خانوادگی"><input name="name" maxLength={120} autoComplete="name" className={inputClass} placeholder="نام شما"/></Field><Field label="شماره موبایل" required><input name="phone" required maxLength={11} inputMode="numeric" autoComplete="tel" dir="ltr" className={`${inputClass} text-left`} placeholder="09123456789"/></Field>
      <Field label="نام کسب‌وکار" required><input name="businessName" required maxLength={160} autoComplete="organization" className={inputClass} placeholder="نام مجموعه یا برند"/></Field><Field label="موضوع فایل" required><select name="fileSubject" required defaultValue="" className={inputClass}><option value="" disabled>انتخاب کنید</option><option value="فروش و سفارش">فروش و سفارش</option><option value="موجودی و کالا">موجودی و کالا</option><option value="مالی و هزینه">مالی و هزینه</option><option value="مشتری و کمپین">مشتری و کمپین</option><option value="عملیات و منابع انسانی">عملیات و منابع انسانی</option><option value="سایر">سایر</option></select></Field>
      <Field label="اندازه تقریبی فایل"><select name="fileSize" defaultValue="" className={inputClass}><option value="">نامشخص</option><option value="کمتر از ۱۰۰۰ ردیف">کمتر از ۱۰۰۰ ردیف</option><option value="۱۰۰۰ تا ۱۰هزار ردیف">۱۰۰۰ تا ۱۰هزار ردیف</option><option value="۱۰هزار تا ۱۰۰هزار ردیف">۱۰هزار تا ۱۰۰هزار ردیف</option><option value="بیشتر از ۱۰۰هزار ردیف">بیشتر از ۱۰۰هزار ردیف</option></select></Field><Field label="روش فعلی تحلیل"><select name="currentMethod" defaultValue="" className={inputClass}><option value="">نامشخص</option><option value="فرمول و Pivot در Excel">فرمول و Pivot در Excel</option><option value="گزارش دستی">گزارش دستی</option><option value="نرم‌افزار دیگر">نرم‌افزار دیگر</option><option value="فعلاً تحلیل نمی‌شود">فعلاً تحلیل نمی‌شود</option></select></Field>
      <div className="sm:col-span-2"><Field label="مهم‌ترین سؤال از فایل" required><input name="mainQuestion" required maxLength={220} className={inputClass} placeholder="مثلاً چرا فروش این ماه کاهش پیدا کرده است؟"/></Field></div><div className="sm:col-span-2"><Field label="آیا فایل شامل داده شخصی یا حساس است؟" required><select name="sensitiveData" required defaultValue="" className={inputClass}><option value="" disabled>انتخاب کنید</option><option value="خیر">خیر</option><option value="بله">بله</option><option value="مطمئن نیستم">مطمئن نیستم</option></select></Field></div>
      <div className="sm:col-span-2"><Field label="توضیح تکمیلی"><textarea name="note" maxLength={600} rows={4} className={`${inputClass} h-auto min-h-28 py-3`} placeholder="ساختار فایل یا خروجی مورد انتظار را بدون درج اطلاعات محرمانه توضیح دهید"/></Field></div><input name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/><label className="font-ui flex items-start gap-2 text-[11px] leading-6 text-marketing-text-muted sm:col-span-2"><input name="consent" type="checkbox" required className="mt-1 accent-[var(--service-accent)]"/><span>با تماس تیم Binix برای بررسی درخواست تحلیل آزمایشی موافقم.</span></label>{error?<div role="alert" className="font-ui rounded-control border border-red-400/20 bg-red-400/[0.06] px-3 py-2 text-xs text-red-200 sm:col-span-2">{error}</div>:null}<button type="submit" disabled={submitting} className="font-ui flex h-12 items-center justify-center gap-2 rounded-control bg-service-accent px-5 text-sm font-bold text-white transition hover:-translate-y-0.5 disabled:cursor-wait disabled:opacity-60 sm:col-span-2">{submitting?"در حال ثبت…":"ثبت درخواست تحلیل آزمایشی"}<Send size={15}/></button><p className="font-ui text-center text-[10.5px] text-marketing-text-subtle sm:col-span-2">قبلاً حساب ساخته‌اید؟ <Link href="/login?service=excel-analyzer" className="font-semibold text-service-accent">ورود به پنل</Link></p>
    </form>}</div></div></section>;
}

function Field({label,required,children}:{label:string;required?:boolean;children:React.ReactNode}){return <label className="font-ui block text-xs text-marketing-text-muted"><span className="mb-2 block">{label}{required?<span className="mr-1 text-service-accent">*</span>:null}</span>{children}</label>}
