const questions = [
  { question: "چه نوع فایل‌هایی قابل بررسی‌اند؟", answer: "تمرکز محصول روی فایل‌های جدولی XLSX، XLS و CSV است که ردیف و ستون مشخص دارند. مناسب‌بودن ساختار در بررسی اولیه مشخص می‌شود." },
  { question: "آیا همین صفحه فایل را دریافت می‌کند؟", answer: "خیر. فرم این صفحه فقط برای درخواست تحلیل آزمایشی است و هیچ فایل شخصی یا سازمانی در آن بارگذاری نمی‌شود. دریافت فایل پس از هماهنگی و تعیین سیاست پردازش انجام می‌شود." },
  { question: "چه خروجی‌ای دریافت می‌کنم؟", answer: "خروجی هدف شامل گزارش کیفیت داده، شاخص‌ها و روندهای متناسب با مسئله، خلاصه مدیریتی و موارد نیازمند بررسی است. خروجی دقیق به ستون‌های موجود بستگی دارد." },
  { question: "آیا تحلیل AI همیشه قطعی است؟", answer: "خیر. پیشنهاد و تفسیر باید از واقعیت داده جدا باشد، محدودیت‌ها را نشان دهد و جای قضاوت مدیر یا کارشناس را نگیرد." },
  { question: "فایل تا چه زمانی نگهداری می‌شود؟", answer: "پیش از فعال‌شدن دریافت واقعی فایل، دوره نگهداری، حذف و سطح دسترسی باید در قرارداد اجرایی روشن شود. در وضعیت فعلی این صفحه فایلی ذخیره نمی‌کند." },
];

export default function ExcelFaq(){return <section dir="rtl" className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-[900px]"><div className="text-center"><div className="font-ui text-[10.5px] font-semibold text-service-accent">پرسش‌های متداول</div><h2 className="font-display mt-3 text-2xl font-black text-marketing-text sm:text-3xl">قبل از سپردن فایل چه چیزهایی باید روشن باشد؟</h2></div><div className="mt-10 space-y-3">{questions.map(item=><details key={item.question} className="group rounded-card border border-marketing-border bg-marketing-surface/55 p-5"><summary className="font-display cursor-pointer list-none text-sm font-bold text-marketing-text marker:hidden"><span className="flex items-center justify-between gap-4">{item.question}<span className="font-ui text-lg font-normal text-service-accent transition group-open:rotate-45">+</span></span></summary><p className="font-ui mt-4 border-t border-marketing-border pt-4 text-[11.5px] leading-7 text-marketing-text-muted">{item.answer}</p></details>)}</div></div></section>}
