"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Check, ChevronRight, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { AppPage } from "@/components/app/app-page";
import { PageHeader } from "@/components/shell/page-header";
import { Badge } from "@/components/ui/badge";
import { Button, ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { checkoutCustomServiceApi, getCustomerCustomOfferApi, type CustomOffer } from "@/lib/api-client/custom-services";
import { getPaymentGatewaysApi, type PaymentGateway } from "@/lib/api-client/payment-gateways";

function money(amount: string) { try { return `${(BigInt(amount) / 10n).toLocaleString("fa-IR")} تومان`; } catch { return "—"; } }
function date(value: string) { return new Date(value).toLocaleString("fa-IR-u-ca-persian", { dateStyle: "long", timeStyle: "short", timeZone: "Asia/Tehran" }); }
function period(offer: CustomOffer) { return offer.billingPeriod === "CUSTOM" ? `${offer.customDurationDays} روز` : offer.billingPeriod === "MONTHLY" ? "یک ماه" : offer.billingPeriod === "QUARTERLY" ? "سه ماه" : "یک سال"; }
export default function CustomOfferPage() {
  const params = useParams<{ offerId: string }>(); const id = params.offerId;
  const [offer, setOffer] = useState<CustomOffer | null>(null); const [gateways, setGateways] = useState<PaymentGateway[]>([]); const [gatewayId, setGatewayId] = useState(""); const [accepted, setAccepted] = useState(false); const [loading, setLoading] = useState(true); const [paying, setPaying] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [offerData, gatewayData] = await Promise.all([getCustomerCustomOfferApi(id), getPaymentGatewaysApi()]); setOffer(offerData.offer); setGateways(gatewayData.gateways); setGatewayId(gatewayData.gateways[0]?.id || ""); } catch (reason) { setError(reason instanceof Error ? reason.message : "پیشنهاد قابل دریافت نیست."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function pay() { if (!gatewayId) return toast.error("درگاه پرداخت را انتخاب کنید."); if (!accepted) return toast.error("ابتدا شرایط پیشنهاد را تأیید کنید."); const gateway = gateways.find((item) => item.id === gatewayId); if (gateway?.provider !== "local-test" && !window.confirm("شما به درگاه واقعی منتقل می‌شوید. پرداخت را ادامه می‌دهید؟")) return; setPaying(true); try { const result = await checkoutCustomServiceApi(id, gatewayId, accepted); window.location.assign(result.checkout.paymentUrl); } catch (reason) { toast.error("ایجاد پرداخت انجام نشد", { description: reason instanceof Error ? reason.message : undefined }); setPaying(false); } }
  return <AppPage width="wide"><PageHeader title="جزئیات پیشنهاد اختصاصی" actions={<ButtonLink href="/app/custom-services" variant="secondary" leadingIcon={<ChevronRight size={15}/>}>بازگشت</ButtonLink>}/>{loading ? <div className="h-72 animate-pulse rounded-card bg-surface-raised"/> : error || !offer ? <Card className="text-center font-ui text-sm text-error">{error || "پیشنهاد پیدا نشد."}</Card> : <div className="grid gap-5 lg:grid-cols-[1fr_360px]">
    <Card><div className="flex items-start justify-between gap-3"><div><p className="font-ui text-xs text-primary">{offer.customService.name}</p><h1 className="mt-1 text-2xl font-bold">{offer.title}</h1></div><Badge variant={offer.status === "PAID" ? "success" : "warning"}>{offer.status === "PAID" ? "پرداخت‌شده" : "قابل پرداخت"}</Badge></div><p className="mt-5 whitespace-pre-line font-ui text-sm leading-8 text-foreground-muted">{offer.description}</p><div className="mt-4 grid gap-2 font-ui text-xs sm:grid-cols-2"><p className="rounded-control bg-surface-raised p-3">مدت سرویس: {period(offer)}</p><p className="rounded-control bg-surface-raised p-3">مهلت پرداخت: {date(offer.validUntil)}</p></div>{offer.features.length > 0 && <div className="mt-6 border-t border-border-subtle pt-5"><h2 className="font-bold">خروجی‌ها و امکانات</h2><ul className="mt-3 space-y-2">{offer.features.map((feature) => <li key={feature} className="flex gap-2 font-ui text-sm text-foreground-muted"><Check size={16} className="mt-0.5 shrink-0 text-success"/>{feature}</li>)}</ul></div>}{offer.terms && <div className="mt-6 rounded-control border border-border bg-surface-raised p-4"><h2 className="font-ui text-sm font-bold">شرایط و تعهدات</h2><p className="mt-2 whitespace-pre-line font-ui text-xs leading-7 text-foreground-muted">{offer.terms}</p></div>}</Card>
    <Card className="h-fit"><h2 className="text-lg font-bold">{offer.status === "PAID" ? "وضعیت فعال‌سازی" : "پرداخت و فعال‌سازی"}</h2><div className="mt-4 rounded-control bg-surface-raised p-4"><p className="font-ui text-xs text-foreground-muted">مبلغ نهایی</p><p className="mt-2 text-xl font-bold">{money(offer.priceAmount)}</p></div>{offer.status === "PAID" ? <><p className="mt-4 rounded-control bg-success/10 p-4 font-ui text-sm leading-7 text-success">پرداخت این پیشنهاد ثبت شده است.{offer.subscription ? ` اشتراک تا ${date(offer.subscription.endsAt)} معتبر است.` : " فعال‌سازی در حال تکمیل است."}</p>{offer.subscription?.status === "ACTIVE" && offer.customService.appHref && <ButtonLink href={offer.customService.appHref} className="mt-4 w-full">ورود به سرویس</ButtonLink>}</> : <><p className="mt-4 font-ui text-xs leading-6 text-foreground-muted">درگاه پرداخت را انتخاب کنید:</p><div className="mt-2 space-y-2">{gateways.map((gateway) => <label key={gateway.id} className={`flex cursor-pointer items-center gap-3 rounded-control border p-3 font-ui text-sm ${gatewayId === gateway.id ? "border-primary bg-primary/5" : "border-border"}`}><input type="radio" name="gateway" value={gateway.id} checked={gatewayId === gateway.id} onChange={() => setGatewayId(gateway.id)}/><span>{gateway.name}</span></label>)}</div>{!gateways.length && <p className="mt-3 rounded-control bg-error/10 p-3 font-ui text-xs text-error">درگاه پرداخت فعالی وجود ندارد؛ با پشتیبانی تماس بگیرید.</p>}<label className="mt-4 flex items-start gap-2 font-ui text-xs leading-6"><input className="mt-1" type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)}/><span>جزئیات، مبلغ و شرایط این پیشنهاد را خوانده‌ام و تأیید می‌کنم.</span></label><Button className="mt-4 w-full" loading={paying} disabled={!gatewayId || !accepted} onClick={() => void pay()}>پرداخت و فعال‌سازی</Button><p className="mt-3 flex gap-2 font-ui text-[11px] leading-6 text-foreground-subtle"><ShieldCheck size={15} className="shrink-0 text-success"/>پس از تأیید موفق پرداخت، اشتراک اختصاصی به‌صورت خودکار فعال می‌شود.</p></>}</Card>
  </div>}</AppPage>;
}
