name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. دریافت کد
      - name: Checkout
        uses: actions/checkout@v4

      # 2. ورود به GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build و Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mostafa001994/binex:latest
            ghcr.io/mostafa001994/binex:${{ github.sha }}

      # 4. Deploy در Portainer
      - name: Redeploy Portainer Stack
        run: |
          curl -f -X POST \
            "${{ secrets.PORTAINER_URL }}/api/stacks/${{ secrets.PORTAINER_STACK_ID }}/git/redeploy?endpointId=${{ secrets.PORTAINER_ENDPOINT_ID }}" \
            -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
