name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mostafa001994/binex:latest
            ghcr.io/mostafa001994/binex:${{ github.sha }}

      - name: Pull Latest Image on Portainer
        run: |
          curl -f -X POST \
            "${{ secrets.PORTAINER_URL }}/api/endpoints/${{ secrets.PORTAINER_ENDPOINT_ID }}/docker/images/create?fromImage=ghcr.io/mostafa001994/binex:latest" \
            -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}"

      - name: Redeploy Stack
        run: |
          curl -f -X POST \
            "${{ secrets.PORTAINER_URL }}/api/stacks/${{ secrets.PORTAINER_STACK_ID }}/start?endpointId=${{ secrets.PORTAINER_ENDPOINT_ID }}" \
            -H "X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}"
